spring:
  sql.init.mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/db_scholarship?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
